export const CITIES = Object.freeze([
  { name: 'Kabupaten Aceh Barat', province: 'Aceh' },
  { name: 'Kabupaten Aceh Barat Daya', province: 'Aceh' },
  { name: 'Kabupaten Aceh Besar', province: 'Aceh' },
  { name: 'Kabupaten Aceh Jaya', province: 'Aceh' },
  { name: 'Kabupaten Aceh Selatan', province: 'Aceh' },
  { name: 'Kabupaten Aceh Singkil', province: 'Aceh' },
  { name: 'Kabupaten Aceh Tamiang', province: 'Aceh' },
  { name: 'Kabupaten Aceh Tengah', province: 'Aceh' },
  { name: 'Kabupaten Aceh Tenggara', province: 'Aceh' },
  { name: 'Kabupaten Aceh Timur', province: 'Aceh' },
  { name: 'Kabupaten Aceh Utara', province: 'Aceh' },
  { name: 'Kabupaten Bener Meriah', province: 'Aceh' },
  { name: 'Kabupaten Bireuen', province: 'Aceh' },
  { name: 'Kabupaten Gayo Lues', province: 'Aceh' },
  { name: 'Kabupaten Nagan Raya', province: 'Aceh' },
  { name: 'Kabupaten Pidie', province: 'Aceh' },
  { name: 'Kabupaten Pidie Jaya', province: 'Aceh' },
  { name: 'Kabupaten Simeulue', province: 'Aceh' },
  { name: 'Kota Banda Aceh', province: 'Aceh' },
  { name: 'Kota Langsa', province: 'Aceh' },
  { name: 'Kota Lhokseumawe', province: 'Aceh' },
  { name: 'Kota Sabang', province: 'Aceh' },
  { name: 'Kota Subulussalam', province: 'Aceh' },
  { name: 'Kabupaten Badung', province: 'Bali' },
  { name: 'Kabupaten Bangli', province: 'Bali' },
  { name: 'Kabupaten Buleleng', province: 'Bali' },
  { name: 'Kabupaten Gianyar', province: 'Bali' },
  { name: 'Kabupaten Jembrana', province: 'Bali' },
  { name: 'Kabupaten Karangasem', province: 'Bali' },
  { name: 'Kabupaten Klungkung', province: 'Bali' },
  { name: 'Kabupaten Tabanan', province: 'Bali' },
  { name: 'Kota Denpasar', province: 'Bali' },
  { name: 'Kabupaten Lebak', province: 'Banten' },
  { name: 'Kabupaten Pandeglang', province: 'Banten' },
  { name: 'Kabupaten Serang', province: 'Banten' },
  { name: 'Kabupaten Tangerang', province: 'Banten' },
  { name: 'Kota Cilegon', province: 'Banten' },
  { name: 'Kota Serang', province: 'Banten' },
  { name: 'Kota Tangerang', province: 'Banten' },
  { name: 'Kota Tangerang Selatan', province: 'Banten' },
  { name: 'Kabupaten Bengkulu Selatan', province: 'Bengkulu' },
  { name: 'Kabupaten Bengkulu Tengah', province: 'Bengkulu' },
  { name: 'Kabupaten Bengkulu Utara', province: 'Bengkulu' },
  { name: 'Kabupaten Kaur', province: 'Bengkulu' },
  { name: 'Kabupaten Kepahiang', province: 'Bengkulu' },
  { name: 'Kabupaten Lebong', province: 'Bengkulu' },
  { name: 'Kabupaten Mukomuko', province: 'Bengkulu' },
  { name: 'Kabupaten Rejang Lebong', province: 'Bengkulu' },
  { name: 'Kabupaten Seluma', province: 'Bengkulu' },
  { name: 'Kota Bengkulu', province: 'Bengkulu' },
  { name: 'Kabupaten Bantul', province: 'Daerah Istimewa Yogyakarta' },
  { name: 'Kabupaten Gunungkidul', province: 'Daerah Istimewa Yogyakarta' },
  { name: 'Kabupaten Kulon Progo', province: 'Daerah Istimewa Yogyakarta' },
  { name: 'Kabupaten Sleman', province: 'Daerah Istimewa Yogyakarta' },
  { name: 'Kota Yogyakarta', province: 'Daerah Istimewa Yogyakarta' },
  { name: 'Kabupaten Administrasi Kepulauan Seribu', province: 'Daerah Khusus Ibukota Jakarta' },
  { name: 'Kota Administrasi Jakarta Barat', province: 'Daerah Khusus Ibukota Jakarta' },
  { name: 'Kota Administrasi Jakarta Pusat', province: 'Daerah Khusus Ibukota Jakarta' },
  { name: 'Kota Administrasi Jakarta Selatan', province: 'Daerah Khusus Ibukota Jakarta' },
  { name: 'Kota Administrasi Jakarta Timur', province: 'Daerah Khusus Ibukota Jakarta' },
  { name: 'Kota Administrasi Jakarta Utara', province: 'Daerah Khusus Ibukota Jakarta' },
  { name: 'Kabupaten Boalemo', province: 'Gorontalo' },
  { name: 'Kabupaten Bone Bolango', province: 'Gorontalo' },
  { name: 'Kabupaten Gorontalo', province: 'Gorontalo' },
  { name: 'Kabupaten Gorontalo Utara', province: 'Gorontalo' },
  { name: 'Kabupaten Pohuwato', province: 'Gorontalo' },
  { name: 'Kota Gorontalo', province: 'Gorontalo' },
  { name: 'Kabupaten Batanghari', province: 'Jambi' },
  { name: 'Kabupaten Bungo', province: 'Jambi' },
  { name: 'Kabupaten Kerinci', province: 'Jambi' },
  { name: 'Kabupaten Merangin', province: 'Jambi' },
  { name: 'Kabupaten Muaro Jambi', province: 'Jambi' },
  { name: 'Kabupaten Sarolangun', province: 'Jambi' },
  { name: 'Kabupaten Tanjung Jabung Barat', province: 'Jambi' },
  { name: 'Kabupaten Tanjung Jabung Timur', province: 'Jambi' },
  { name: 'Kabupaten Tebo', province: 'Jambi' },
  { name: 'Kota Jambi', province: 'Jambi' },
  { name: 'Kota Sungai Penuh', province: 'Jambi' },
  { name: 'Kabupaten Bandung', province: 'Jawa Barat' },
  { name: 'Kabupaten Bandung Barat', province: 'Jawa Barat' },
  { name: 'Kabupaten Bekasi', province: 'Jawa Barat' },
  { name: 'Kabupaten Bogor', province: 'Jawa Barat' },
  { name: 'Kabupaten Ciamis', province: 'Jawa Barat' },
  { name: 'Kabupaten Cianjur', province: 'Jawa Barat' },
  { name: 'Kabupaten Cirebon', province: 'Jawa Barat' },
  { name: 'Kabupaten Garut', province: 'Jawa Barat' },
  { name: 'Kabupaten Indramayu', province: 'Jawa Barat' },
  { name: 'Kabupaten Karawang', province: 'Jawa Barat' },
  { name: 'Kabupaten Kuningan', province: 'Jawa Barat' },
  { name: 'Kabupaten Majalengka', province: 'Jawa Barat' },
  { name: 'Kabupaten Pangandaran', province: 'Jawa Barat' },
  { name: 'Kabupaten Purwakarta', province: 'Jawa Barat' },
  { name: 'Kabupaten Subang', province: 'Jawa Barat' },
  { name: 'Kabupaten Sukabumi', province: 'Jawa Barat' },
  { name: 'Kabupaten Sumedang', province: 'Jawa Barat' },
  { name: 'Kabupaten Tasikmalaya', province: 'Jawa Barat' },
  { name: 'Kota Bandung', province: 'Jawa Barat' },
  { name: 'Kota Banjar', province: 'Jawa Barat' },
  { name: 'Kota Bekasi', province: 'Jawa Barat' },
  { name: 'Kota Bogor', province: 'Jawa Barat' },
  { name: 'Kota Cimahi', province: 'Jawa Barat' },
  { name: 'Kota Cirebon', province: 'Jawa Barat' },
  { name: 'Kota Depok', province: 'Jawa Barat' },
  { name: 'Kota Sukabumi', province: 'Jawa Barat' },
  { name: 'Kota Tasikmalaya', province: 'Jawa Barat' },
  { name: 'Kabupaten Banjarnegara', province: 'Jawa Tengah' },
  { name: 'Kabupaten Banyumas', province: 'Jawa Tengah' },
  { name: 'Kabupaten Batang', province: 'Jawa Tengah' },
  { name: 'Kabupaten Blora', province: 'Jawa Tengah' },
  { name: 'Kabupaten Boyolali', province: 'Jawa Tengah' },
  { name: 'Kabupaten Brebes', province: 'Jawa Tengah' },
  { name: 'Kabupaten Cilacap', province: 'Jawa Tengah' },
  { name: 'Kabupaten Demak', province: 'Jawa Tengah' },
  { name: 'Kabupaten Grobogan', province: 'Jawa Tengah' },
  { name: 'Kabupaten Jepara', province: 'Jawa Tengah' },
  { name: 'Kabupaten Karanganyar', province: 'Jawa Tengah' },
  { name: 'Kabupaten Kebumen', province: 'Jawa Tengah' },
  { name: 'Kabupaten Kendal', province: 'Jawa Tengah' },
  { name: 'Kabupaten Klaten', province: 'Jawa Tengah' },
  { name: 'Kabupaten Kudus', province: 'Jawa Tengah' },
  { name: 'Kabupaten Magelang', province: 'Jawa Tengah' },
  { name: 'Kabupaten Pati', province: 'Jawa Tengah' },
  { name: 'Kabupaten Pekalongan', province: 'Jawa Tengah' },
  { name: 'Kabupaten Pemalang', province: 'Jawa Tengah' },
  { name: 'Kabupaten Purbalingga', province: 'Jawa Tengah' },
  { name: 'Kabupaten Purworejo', province: 'Jawa Tengah' },
  { name: 'Kabupaten Rembang', province: 'Jawa Tengah' },
  { name: 'Kabupaten Semarang', province: 'Jawa Tengah' },
  { name: 'Kabupaten Sragen', province: 'Jawa Tengah' },
  { name: 'Kabupaten Sukoharjo', province: 'Jawa Tengah' },
  { name: 'Kabupaten Tegal', province: 'Jawa Tengah' },
  { name: 'Kabupaten Temanggung', province: 'Jawa Tengah' },
  { name: 'Kabupaten Wonogiri', province: 'Jawa Tengah' },
  { name: 'Kabupaten Wonosobo', province: 'Jawa Tengah' },
  { name: 'Kota Magelang', province: 'Jawa Tengah' },
  { name: 'Kota Pekalongan', province: 'Jawa Tengah' },
  { name: 'Kota Salatiga', province: 'Jawa Tengah' },
  { name: 'Kota Semarang', province: 'Jawa Tengah' },
  { name: 'Kota Surakarta', province: 'Jawa Tengah' },
  { name: 'Kota Tegal', province: 'Jawa Tengah' },
  { name: 'Kabupaten Bangkalan', province: 'Jawa Timur' },
  { name: 'Kabupaten Banyuwangi', province: 'Jawa Timur' },
  { name: 'Kabupaten Blitar', province: 'Jawa Timur' },
  { name: 'Kabupaten Bojonegoro', province: 'Jawa Timur' },
  { name: 'Kabupaten Bondowoso', province: 'Jawa Timur' },
  { name: 'Kabupaten Gresik', province: 'Jawa Timur' },
  { name: 'Kabupaten Jember', province: 'Jawa Timur' },
  { name: 'Kabupaten Jombang', province: 'Jawa Timur' },
  { name: 'Kabupaten Kediri', province: 'Jawa Timur' },
  { name: 'Kabupaten Lamongan', province: 'Jawa Timur' },
  { name: 'Kabupaten Lumajang', province: 'Jawa Timur' },
  { name: 'Kabupaten Madiun', province: 'Jawa Timur' },
  { name: 'Kabupaten Magetan', province: 'Jawa Timur' },
  { name: 'Kabupaten Malang', province: 'Jawa Timur' },
  { name: 'Kabupaten Mojokerto', province: 'Jawa Timur' },
  { name: 'Kabupaten Nganjuk', province: 'Jawa Timur' },
  { name: 'Kabupaten Ngawi', province: 'Jawa Timur' },
  { name: 'Kabupaten Pacitan', province: 'Jawa Timur' },
  { name: 'Kabupaten Pamekasan', province: 'Jawa Timur' },
  { name: 'Kabupaten Pasuruan', province: 'Jawa Timur' },
  { name: 'Kabupaten Ponorogo', province: 'Jawa Timur' },
  { name: 'Kabupaten Probolinggo', province: 'Jawa Timur' },
  { name: 'Kabupaten Sampang', province: 'Jawa Timur' },
  { name: 'Kabupaten Sidoarjo', province: 'Jawa Timur' },
  { name: 'Kabupaten Situbondo', province: 'Jawa Timur' },
  { name: 'Kabupaten Sumenep', province: 'Jawa Timur' },
  { name: 'Kabupaten Trenggalek', province: 'Jawa Timur' },
  { name: 'Kabupaten Tuban', province: 'Jawa Timur' },
  { name: 'Kabupaten Tulungagung', province: 'Jawa Timur' },
  { name: 'Kota Batu', province: 'Jawa Timur' },
  { name: 'Kota Blitar', province: 'Jawa Timur' },
  { name: 'Kota Kediri', province: 'Jawa Timur' },
  { name: 'Kota Madiun', province: 'Jawa Timur' },
  { name: 'Kota Malang', province: 'Jawa Timur' },
  { name: 'Kota Mojokerto', province: 'Jawa Timur' },
  { name: 'Kota Pasuruan', province: 'Jawa Timur' },
  { name: 'Kota Probolinggo', province: 'Jawa Timur' },
  { name: 'Kota Surabaya', province: 'Jawa Timur' },
  { name: 'Kabupaten Bengkayang', province: 'Kalimantan Barat' },
  { name: 'Kabupaten Kapuas Hulu', province: 'Kalimantan Barat' },
  { name: 'Kabupaten Kayong Utara', province: 'Kalimantan Barat' },
  { name: 'Kabupaten Ketapang', province: 'Kalimantan Barat' },
  { name: 'Kabupaten Kubu Raya', province: 'Kalimantan Barat' },
  { name: 'Kabupaten Landak', province: 'Kalimantan Barat' },
  { name: 'Kabupaten Melawi', province: 'Kalimantan Barat' },
  { name: 'Kabupaten Mempawah', province: 'Kalimantan Barat' },
  { name: 'Kabupaten Sambas', province: 'Kalimantan Barat' },
  { name: 'Kabupaten Sanggau', province: 'Kalimantan Barat' },
  { name: 'Kabupaten Sekadau', province: 'Kalimantan Barat' },
  { name: 'Kabupaten Sintang', province: 'Kalimantan Barat' },
  { name: 'Kota Pontianak', province: 'Kalimantan Barat' },
  { name: 'Kota Singkawang', province: 'Kalimantan Barat' },
  { name: 'Kabupaten Balangan', province: 'Kalimantan Selatan' },
  { name: 'Kabupaten Banjar', province: 'Kalimantan Selatan' },
  { name: 'Kabupaten Barito Kuala', province: 'Kalimantan Selatan' },
  { name: 'Kabupaten Hulu Sungai Selatan', province: 'Kalimantan Selatan' },
  { name: 'Kabupaten Hulu Sungai Tengah', province: 'Kalimantan Selatan' },
  { name: 'Kabupaten Hulu Sungai Utara', province: 'Kalimantan Selatan' },
  { name: 'Kabupaten Kotabaru', province: 'Kalimantan Selatan' },
  { name: 'Kabupaten Tabalong', province: 'Kalimantan Selatan' },
  { name: 'Kabupaten Tanah Bumbu', province: 'Kalimantan Selatan' },
  { name: 'Kabupaten Tanah Laut', province: 'Kalimantan Selatan' },
  { name: 'Kabupaten Tapin', province: 'Kalimantan Selatan' },
  { name: 'Kota Banjarbaru', province: 'Kalimantan Selatan' },
  { name: 'Kota Banjarmasin', province: 'Kalimantan Selatan' },
  { name: 'Kabupaten Barito Selatan', province: 'Kalimantan Tengah' },
  { name: 'Kabupaten Barito Timur', province: 'Kalimantan Tengah' },
  { name: 'Kabupaten Barito Utara', province: 'Kalimantan Tengah' },
  { name: 'Kabupaten Gunung Mas', province: 'Kalimantan Tengah' },
  { name: 'Kabupaten Kapuas', province: 'Kalimantan Tengah' },
  { name: 'Kabupaten Katingan', province: 'Kalimantan Tengah' },
  { name: 'Kabupaten Kotawaringin Barat', province: 'Kalimantan Tengah' },
  { name: 'Kabupaten Kotawaringin Timur', province: 'Kalimantan Tengah' },
  { name: 'Kabupaten Lamandau', province: 'Kalimantan Tengah' },
  { name: 'Kabupaten Murung Raya', province: 'Kalimantan Tengah' },
  { name: 'Kabupaten Pulang Pisau', province: 'Kalimantan Tengah' },
  { name: 'Kabupaten Seruyan', province: 'Kalimantan Tengah' },
  { name: 'Kabupaten Sukamara', province: 'Kalimantan Tengah' },
  { name: 'Kota Palangkaraya', province: 'Kalimantan Tengah' },
  { name: 'Kabupaten Berau', province: 'Kalimantan Timur' },
  { name: 'Kabupaten Kutai Barat', province: 'Kalimantan Timur' },
  { name: 'Kabupaten Kutai Kartanegara', province: 'Kalimantan Timur' },
  { name: 'Kabupaten Kutai Timur', province: 'Kalimantan Timur' },
  { name: 'Kabupaten Mahakam Ulu', province: 'Kalimantan Timur' },
  { name: 'Kabupaten Paser', province: 'Kalimantan Timur' },
  { name: 'Kabupaten Penajam Paser Utara', province: 'Kalimantan Timur' },
  { name: 'Kota Balikpapan', province: 'Kalimantan Timur' },
  { name: 'Kota Bontang', province: 'Kalimantan Timur' },
  { name: 'Kota Samarinda', province: 'Kalimantan Timur' },
  { name: 'Kabupaten Bulungan', province: 'Kalimantan Utara' },
  { name: 'Kabupaten Malinau', province: 'Kalimantan Utara' },
  { name: 'Kabupaten Nunukan', province: 'Kalimantan Utara' },
  { name: 'Kabupaten Tana Tidung', province: 'Kalimantan Utara' },
  { name: 'Kota Tarakan', province: 'Kalimantan Utara' },
  { name: 'Kabupaten Bangka', province: 'Kepulauan Bangka Belitung' },
  { name: 'Kabupaten Bangka Barat', province: 'Kepulauan Bangka Belitung' },
  { name: 'Kabupaten Bangka Selatan', province: 'Kepulauan Bangka Belitung' },
  { name: 'Kabupaten Bangka Tengah', province: 'Kepulauan Bangka Belitung' },
  { name: 'Kabupaten Belitung', province: 'Kepulauan Bangka Belitung' },
  { name: 'Kabupaten Belitung Timur', province: 'Kepulauan Bangka Belitung' },
  { name: 'Kota Pangkal Pinang', province: 'Kepulauan Bangka Belitung' },
  { name: 'Kabupaten Bintan', province: 'Kepulauan Riau' },
  { name: 'Kabupaten Karimun', province: 'Kepulauan Riau' },
  { name: 'Kabupaten Kepulauan Anambas', province: 'Kepulauan Riau' },
  { name: 'Kabupaten Lingga', province: 'Kepulauan Riau' },
  { name: 'Kabupaten Natuna', province: 'Kepulauan Riau' },
  { name: 'Kota Batam', province: 'Kepulauan Riau' },
  { name: 'Kota Tanjung Pinang', province: 'Kepulauan Riau' },
  { name: 'Kabupaten Lampung Barat', province: 'Lampung' },
  { name: 'Kabupaten Lampung Selatan', province: 'Lampung' },
  { name: 'Kabupaten Lampung Tengah', province: 'Lampung' },
  { name: 'Kabupaten Lampung Timur', province: 'Lampung' },
  { name: 'Kabupaten Lampung Utara', province: 'Lampung' },
  { name: 'Kabupaten Mesuji', province: 'Lampung' },
  { name: 'Kabupaten Pesawaran', province: 'Lampung' },
  { name: 'Kabupaten Pesisir Barat', province: 'Lampung' },
  { name: 'Kabupaten Pringsewu', province: 'Lampung' },
  { name: 'Kabupaten Tanggamus', province: 'Lampung' },
  { name: 'Kabupaten Tulang Bawang', province: 'Lampung' },
  { name: 'Kabupaten Tulang Bawang Barat', province: 'Lampung' },
  { name: 'Kabupaten Way Kanan', province: 'Lampung' },
  { name: 'Kota Bandar Lampung', province: 'Lampung' },
  { name: 'Kota Metro', province: 'Lampung' },
  { name: 'Kabupaten Buru', province: 'Maluku' },
  { name: 'Kabupaten Buru Selatan', province: 'Maluku' },
  { name: 'Kabupaten Kepulauan Aru', province: 'Maluku' },
  { name: 'Kabupaten Kepulauan Tanimbar', province: 'Maluku' },
  { name: 'Kabupaten Maluku Barat Daya', province: 'Maluku' },
  { name: 'Kabupaten Maluku Tengah', province: 'Maluku' },
  { name: 'Kabupaten Maluku Tenggara', province: 'Maluku' },
  { name: 'Kabupaten Seram Bagian Barat', province: 'Maluku' },
  { name: 'Kabupaten Seram Bagian Timur', province: 'Maluku' },
  { name: 'Kota Ambon', province: 'Maluku' },
  { name: 'Kota Tual', province: 'Maluku' },
  { name: 'Kabupaten Halmahera Barat', province: 'Maluku Utara' },
  { name: 'Kabupaten Halmahera Selatan', province: 'Maluku Utara' },
  { name: 'Kabupaten Halmahera Tengah', province: 'Maluku Utara' },
  { name: 'Kabupaten Halmahera Timur', province: 'Maluku Utara' },
  { name: 'Kabupaten Halmahera Utara', province: 'Maluku Utara' },
  { name: 'Kabupaten Kepulauan Sula', province: 'Maluku Utara' },
  { name: 'Kabupaten Pulau Morotai', province: 'Maluku Utara' },
  { name: 'Kabupaten Pulau Taliabu', province: 'Maluku Utara' },
  { name: 'Kota Ternate', province: 'Maluku Utara' },
  { name: 'Kota Tidore Kepulauan', province: 'Maluku Utara' },
  { name: 'Kabupaten Bima', province: 'Nusa Tenggara Barat' },
  { name: 'Kabupaten Dompu', province: 'Nusa Tenggara Barat' },
  { name: 'Kabupaten Lombok Barat', province: 'Nusa Tenggara Barat' },
  { name: 'Kabupaten Lombok Tengah', province: 'Nusa Tenggara Barat' },
  { name: 'Kabupaten Lombok Timur', province: 'Nusa Tenggara Barat' },
  { name: 'Kabupaten Lombok Utara', province: 'Nusa Tenggara Barat' },
  { name: 'Kabupaten Sumbawa', province: 'Nusa Tenggara Barat' },
  { name: 'Kabupaten Sumbawa Barat', province: 'Nusa Tenggara Barat' },
  { name: 'Kota Bima', province: 'Nusa Tenggara Barat' },
  { name: 'Kota Mataram', province: 'Nusa Tenggara Barat' },
  { name: 'Kabupaten Alor', province: 'Nusa Tenggara Timur' },
  { name: 'Kabupaten Belu', province: 'Nusa Tenggara Timur' },
  { name: 'Kabupaten Ende', province: 'Nusa Tenggara Timur' },
  { name: 'Kabupaten Flores Timur', province: 'Nusa Tenggara Timur' },
  { name: 'Kabupaten Kupang', province: 'Nusa Tenggara Timur' },
  { name: 'Kabupaten Lembata', province: 'Nusa Tenggara Timur' },
  { name: 'Kabupaten Malaka', province: 'Nusa Tenggara Timur' },
  { name: 'Kabupaten Manggarai', province: 'Nusa Tenggara Timur' },
  { name: 'Kabupaten Manggarai Barat', province: 'Nusa Tenggara Timur' },
  { name: 'Kabupaten Manggarai Timur', province: 'Nusa Tenggara Timur' },
  { name: 'Kabupaten Nagekeo', province: 'Nusa Tenggara Timur' },
  { name: 'Kabupaten Ngada', province: 'Nusa Tenggara Timur' },
  { name: 'Kabupaten Rote Ndao', province: 'Nusa Tenggara Timur' },
  { name: 'Kabupaten Sabu Raijua', province: 'Nusa Tenggara Timur' },
  { name: 'Kabupaten Sikka', province: 'Nusa Tenggara Timur' },
  { name: 'Kabupaten Sumba Barat', province: 'Nusa Tenggara Timur' },
  { name: 'Kabupaten Sumba Barat Daya', province: 'Nusa Tenggara Timur' },
  { name: 'Kabupaten Sumba Tengah', province: 'Nusa Tenggara Timur' },
  { name: 'Kabupaten Sumba Timur', province: 'Nusa Tenggara Timur' },
  { name: 'Kabupaten Timor Tengah Selatan', province: 'Nusa Tenggara Timur' },
  { name: 'Kabupaten Timor Tengah Utara', province: 'Nusa Tenggara Timur' },
  { name: 'Kota Kupang', province: 'Nusa Tenggara Timur' },
  { name: 'Kabupaten Biak Numfor', province: 'Papua' },
  { name: 'Kabupaten Jayapura', province: 'Papua' },
  { name: 'Kabupaten Keerom', province: 'Papua' },
  { name: 'Kabupaten Kepulauan Yapen', province: 'Papua' },
  { name: 'Kabupaten Mamberamo Raya', province: 'Papua' },
  { name: 'Kabupaten Sarmi', province: 'Papua' },
  { name: 'Kabupaten Supiori', province: 'Papua' },
  { name: 'Kabupaten Waropen', province: 'Papua' },
  { name: 'Kota Jayapura', province: 'Papua' },
  { name: 'Kabupaten Fak Fak', province: 'Papua Barat' },
  { name: 'Kabupaten Kaimana', province: 'Papua Barat' },
  { name: 'Kabupaten Manokwari', province: 'Papua Barat' },
  { name: 'Kabupaten Manokwari Selatan', province: 'Papua Barat' },
  { name: 'Kabupaten Pegunungan Arfak', province: 'Papua Barat' },
  { name: 'Kabupaten Teluk Bintuni', province: 'Papua Barat' },
  { name: 'Kabupaten Teluk Wondama', province: 'Papua Barat' },
  { name: 'Kabupaten Maybrat', province: 'Papua Barat Daya' },
  { name: 'Kabupaten Raja Ampat', province: 'Papua Barat Daya' },
  { name: 'Kabupaten Sorong', province: 'Papua Barat Daya' },
  { name: 'Kabupaten Sorong Selatan', province: 'Papua Barat Daya' },
  { name: 'Kabupaten Tambrauw', province: 'Papua Barat Daya' },
  { name: 'Kota Sorong', province: 'Papua Barat Daya' },
  { name: 'Kabupaten Jayawijaya', province: 'Papua Pegunungan' },
  { name: 'Kabupaten Lanny Jaya', province: 'Papua Pegunungan' },
  { name: 'Kabupaten Mamberamo Tengah', province: 'Papua Pegunungan' },
  { name: 'Kabupaten Nduga', province: 'Papua Pegunungan' },
  { name: 'Kabupaten Pegunungan Bintang', province: 'Papua Pegunungan' },
  { name: 'Kabupaten Tolikara', province: 'Papua Pegunungan' },
  { name: 'Kabupaten Yahukimo', province: 'Papua Pegunungan' },
  { name: 'Kabupaten Yalimo', province: 'Papua Pegunungan' },
  { name: 'Kabupaten Asmat', province: 'Papua Selatan' },
  { name: 'Kabupaten Boven Digoel', province: 'Papua Selatan' },
  { name: 'Kabupaten Mappi', province: 'Papua Selatan' },
  { name: 'Kabupaten Merauke', province: 'Papua Selatan' },
  { name: 'Kabupaten Deiyai', province: 'Papua Tengah' },
  { name: 'Kabupaten Dogiyai', province: 'Papua Tengah' },
  { name: 'Kabupaten Intan Jaya', province: 'Papua Tengah' },
  { name: 'Kabupaten Mimika', province: 'Papua Tengah' },
  { name: 'Kabupaten Nabire', province: 'Papua Tengah' },
  { name: 'Kabupaten Paniai', province: 'Papua Tengah' },
  { name: 'Kabupaten Puncak', province: 'Papua Tengah' },
  { name: 'Kabupaten Puncak Jaya', province: 'Papua Tengah' },
  { name: 'Kabupaten Bengkalis', province: 'Riau' },
  { name: 'Kabupaten Indragiri Hilir', province: 'Riau' },
  { name: 'Kabupaten Indragiri Hulu', province: 'Riau' },
  { name: 'Kabupaten Kampar', province: 'Riau' },
  { name: 'Kabupaten Kepulauan Meranti', province: 'Riau' },
  { name: 'Kabupaten Kuantan Singingi', province: 'Riau' },
  { name: 'Kabupaten Pelalawan', province: 'Riau' },
  { name: 'Kabupaten Rokan Hilir', province: 'Riau' },
  { name: 'Kabupaten Rokan Hulu', province: 'Riau' },
  { name: 'Kabupaten Siak', province: 'Riau' },
  { name: 'Kota Dumai', province: 'Riau' },
  { name: 'Kota Pekanbaru', province: 'Riau' },
  { name: 'Kabupaten Majene', province: 'Sulawesi Barat' },
  { name: 'Kabupaten Mamasa', province: 'Sulawesi Barat' },
  { name: 'Kabupaten Mamuju', province: 'Sulawesi Barat' },
  { name: 'Kabupaten Mamuju Tengah', province: 'Sulawesi Barat' },
  { name: 'Kabupaten Pasangkayu', province: 'Sulawesi Barat' },
  { name: 'Kabupaten Polewali Mandar', province: 'Sulawesi Barat' },
  { name: 'Kabupaten Bantaeng', province: 'Sulawesi Selatan' },
  { name: 'Kabupaten Barru', province: 'Sulawesi Selatan' },
  { name: 'Kabupaten Bone', province: 'Sulawesi Selatan' },
  { name: 'Kabupaten Bulukumba', province: 'Sulawesi Selatan' },
  { name: 'Kabupaten Enrekang', province: 'Sulawesi Selatan' },
  { name: 'Kabupaten Gowa', province: 'Sulawesi Selatan' },
  { name: 'Kabupaten Jeneponto', province: 'Sulawesi Selatan' },
  { name: 'Kabupaten Kepulauan Selayar', province: 'Sulawesi Selatan' },
  { name: 'Kabupaten Luwu', province: 'Sulawesi Selatan' },
  { name: 'Kabupaten Luwu Timur', province: 'Sulawesi Selatan' },
  { name: 'Kabupaten Luwu Utara', province: 'Sulawesi Selatan' },
  { name: 'Kabupaten Maros', province: 'Sulawesi Selatan' },
  { name: 'Kabupaten Pangkajene dan Kepulauan', province: 'Sulawesi Selatan' },
  { name: 'Kabupaten Pinrang', province: 'Sulawesi Selatan' },
  { name: 'Kabupaten Sidenreng Rappang', province: 'Sulawesi Selatan' },
  { name: 'Kabupaten Sinjai', province: 'Sulawesi Selatan' },
  { name: 'Kabupaten Soppeng', province: 'Sulawesi Selatan' },
  { name: 'Kabupaten Takalar', province: 'Sulawesi Selatan' },
  { name: 'Kabupaten Tana Toraja', province: 'Sulawesi Selatan' },
  { name: 'Kabupaten Toraja Utara', province: 'Sulawesi Selatan' },
  { name: 'Kabupaten Wajo', province: 'Sulawesi Selatan' },
  { name: 'Kota Makassar', province: 'Sulawesi Selatan' },
  { name: 'Kota Palopo', province: 'Sulawesi Selatan' },
  { name: 'Kota Parepare', province: 'Sulawesi Selatan' },
  { name: 'Kabupaten Banggai', province: 'Sulawesi Tengah' },
  { name: 'Kabupaten Banggai Kepulauan', province: 'Sulawesi Tengah' },
  { name: 'Kabupaten Banggai Laut', province: 'Sulawesi Tengah' },
  { name: 'Kabupaten Buol', province: 'Sulawesi Tengah' },
  { name: 'Kabupaten Donggala', province: 'Sulawesi Tengah' },
  { name: 'Kabupaten Morowali', province: 'Sulawesi Tengah' },
  { name: 'Kabupaten Morowali Utara', province: 'Sulawesi Tengah' },
  { name: 'Kabupaten Parigi Moutong', province: 'Sulawesi Tengah' },
  { name: 'Kabupaten Poso', province: 'Sulawesi Tengah' },
  { name: 'Kabupaten Sigi', province: 'Sulawesi Tengah' },
  { name: 'Kabupaten Tojo Una Una', province: 'Sulawesi Tengah' },
  { name: 'Kabupaten Toli-Toli', province: 'Sulawesi Tengah' },
  { name: 'Kota Palu', province: 'Sulawesi Tengah' },
  { name: 'Kabupaten Bombana', province: 'Sulawesi Tenggara' },
  { name: 'Kabupaten Buton', province: 'Sulawesi Tenggara' },
  { name: 'Kabupaten Buton Selatan', province: 'Sulawesi Tenggara' },
  { name: 'Kabupaten Buton Tengah', province: 'Sulawesi Tenggara' },
  { name: 'Kabupaten Buton Utara', province: 'Sulawesi Tenggara' },
  { name: 'Kabupaten Kolaka', province: 'Sulawesi Tenggara' },
  { name: 'Kabupaten Kolaka Timur', province: 'Sulawesi Tenggara' },
  { name: 'Kabupaten Kolaka Utara', province: 'Sulawesi Tenggara' },
  { name: 'Kabupaten Konawe', province: 'Sulawesi Tenggara' },
  { name: 'Kabupaten Konawe Kepulauan', province: 'Sulawesi Tenggara' },
  { name: 'Kabupaten Konawe Selatan', province: 'Sulawesi Tenggara' },
  { name: 'Kabupaten Konawe Utara', province: 'Sulawesi Tenggara' },
  { name: 'Kabupaten Muna', province: 'Sulawesi Tenggara' },
  { name: 'Kabupaten Muna Barat', province: 'Sulawesi Tenggara' },
  { name: 'Kabupaten Wakatobi', province: 'Sulawesi Tenggara' },
  { name: 'Kota Bau Bau', province: 'Sulawesi Tenggara' },
  { name: 'Kota Kendari', province: 'Sulawesi Tenggara' },
  { name: 'Kabupaten Bolaang Mongondow', province: 'Sulawesi Utara' },
  { name: 'Kabupaten Bolaang Mongondow Selatan', province: 'Sulawesi Utara' },
  { name: 'Kabupaten Bolaang Mongondow Timur', province: 'Sulawesi Utara' },
  { name: 'Kabupaten Bolaang Mongondow Utara', province: 'Sulawesi Utara' },
  { name: 'Kabupaten Kep. Siau Tagulandang Biaro', province: 'Sulawesi Utara' },
  { name: 'Kabupaten Kepulauan Sangihe', province: 'Sulawesi Utara' },
  { name: 'Kabupaten Kepulauan Talaud', province: 'Sulawesi Utara' },
  { name: 'Kabupaten Minahasa', province: 'Sulawesi Utara' },
  { name: 'Kabupaten Minahasa Selatan', province: 'Sulawesi Utara' },
  { name: 'Kabupaten Minahasa Tenggara', province: 'Sulawesi Utara' },
  { name: 'Kabupaten Minahasa Utara', province: 'Sulawesi Utara' },
  { name: 'Kota Bitung', province: 'Sulawesi Utara' },
  { name: 'Kota Kotamobagu', province: 'Sulawesi Utara' },
  { name: 'Kota Manado', province: 'Sulawesi Utara' },
  { name: 'Kota Tomohon', province: 'Sulawesi Utara' },
  { name: 'Kabupaten Agam', province: 'Sumatera Barat' },
  { name: 'Kabupaten Dharmasraya', province: 'Sumatera Barat' },
  { name: 'Kabupaten Kepulauan Mentawai', province: 'Sumatera Barat' },
  { name: 'Kabupaten Lima Puluh Kota', province: 'Sumatera Barat' },
  { name: 'Kabupaten Padang Pariaman', province: 'Sumatera Barat' },
  { name: 'Kabupaten Pasaman', province: 'Sumatera Barat' },
  { name: 'Kabupaten Pasaman Barat', province: 'Sumatera Barat' },
  { name: 'Kabupaten Pesisir Selatan', province: 'Sumatera Barat' },
  { name: 'Kabupaten Sijunjung', province: 'Sumatera Barat' },
  { name: 'Kabupaten Solok', province: 'Sumatera Barat' },
  { name: 'Kabupaten Solok Selatan', province: 'Sumatera Barat' },
  { name: 'Kabupaten Tanah Datar', province: 'Sumatera Barat' },
  { name: 'Kota Bukittinggi', province: 'Sumatera Barat' },
  { name: 'Kota Padang', province: 'Sumatera Barat' },
  { name: 'Kota Padang Panjang', province: 'Sumatera Barat' },
  { name: 'Kota Pariaman', province: 'Sumatera Barat' },
  { name: 'Kota Payakumbuh', province: 'Sumatera Barat' },
  { name: 'Kota Sawahlunto', province: 'Sumatera Barat' },
  { name: 'Kota Solok', province: 'Sumatera Barat' },
  { name: 'Kabupaten Banyuasin', province: 'Sumatera Selatan' },
  { name: 'Kabupaten Empat Lawang', province: 'Sumatera Selatan' },
  { name: 'Kabupaten Lahat', province: 'Sumatera Selatan' },
  { name: 'Kabupaten Muara Enim', province: 'Sumatera Selatan' },
  { name: 'Kabupaten Musi Banyuasin', province: 'Sumatera Selatan' },
  { name: 'Kabupaten Musi Rawas', province: 'Sumatera Selatan' },
  { name: 'Kabupaten Musi Rawas Utara', province: 'Sumatera Selatan' },
  { name: 'Kabupaten Ogan Ilir', province: 'Sumatera Selatan' },
  { name: 'Kabupaten Ogan Komering Ilir', province: 'Sumatera Selatan' },
  { name: 'Kabupaten Ogan Komering Ulu', province: 'Sumatera Selatan' },
  { name: 'Kabupaten Ogan Komering Ulu Selatan', province: 'Sumatera Selatan' },
  { name: 'Kabupaten Ogan Komering Ulu Timur', province: 'Sumatera Selatan' },
  { name: 'Kabupaten Penukal Abab Lematang Ilir', province: 'Sumatera Selatan' },
  { name: 'Kota Lubuk Linggau', province: 'Sumatera Selatan' },
  { name: 'Kota Pagar Alam', province: 'Sumatera Selatan' },
  { name: 'Kota Palembang', province: 'Sumatera Selatan' },
  { name: 'Kota Prabumulih', province: 'Sumatera Selatan' },
  { name: 'Kabupaten Asahan', province: 'Sumatera Utara' },
  { name: 'Kabupaten Batu Bara', province: 'Sumatera Utara' },
  { name: 'Kabupaten Dairi', province: 'Sumatera Utara' },
  { name: 'Kabupaten Deli Serdang', province: 'Sumatera Utara' },
  { name: 'Kabupaten Humbang Hasundutan', province: 'Sumatera Utara' },
  { name: 'Kabupaten Karo', province: 'Sumatera Utara' },
  { name: 'Kabupaten Labuhanbatu', province: 'Sumatera Utara' },
  { name: 'Kabupaten Labuhanbatu Selatan', province: 'Sumatera Utara' },
  { name: 'Kabupaten Labuhanbatu Utara', province: 'Sumatera Utara' },
  { name: 'Kabupaten Langkat', province: 'Sumatera Utara' },
  { name: 'Kabupaten Mandailing Natal', province: 'Sumatera Utara' },
  { name: 'Kabupaten Nias', province: 'Sumatera Utara' },
  { name: 'Kabupaten Nias Barat', province: 'Sumatera Utara' },
  { name: 'Kabupaten Nias Selatan', province: 'Sumatera Utara' },
  { name: 'Kabupaten Nias Utara', province: 'Sumatera Utara' },
  { name: 'Kabupaten Padang Lawas', province: 'Sumatera Utara' },
  { name: 'Kabupaten Padang Lawas Utara', province: 'Sumatera Utara' },
  { name: 'Kabupaten Pakpak Bharat', province: 'Sumatera Utara' },
  { name: 'Kabupaten Samosir', province: 'Sumatera Utara' },
  { name: 'Kabupaten Serdang Bedagai', province: 'Sumatera Utara' },
  { name: 'Kabupaten Simalungun', province: 'Sumatera Utara' },
  { name: 'Kabupaten Tapanuli Selatan', province: 'Sumatera Utara' },
  { name: 'Kabupaten Tapanuli Tengah', province: 'Sumatera Utara' },
  { name: 'Kabupaten Tapanuli Utara', province: 'Sumatera Utara' },
  { name: 'Kabupaten Toba', province: 'Sumatera Utara' },
  { name: 'Kota Binjai', province: 'Sumatera Utara' },
  { name: 'Kota Gunungsitoli', province: 'Sumatera Utara' },
  { name: 'Kota Medan', province: 'Sumatera Utara' },
  { name: 'Kota Padangsidimpuan', province: 'Sumatera Utara' },
  { name: 'Kota Pematangsiantar', province: 'Sumatera Utara' },
  { name: 'Kota Sibolga', province: 'Sumatera Utara' },
  { name: 'Kota Tanjungbalai', province: 'Sumatera Utara' },
  { name: 'Kota Tebing Tinggi', province: 'Sumatera Utara' },
]);

export const CITY_NAMES = Object.freeze(CITIES.map((city) => city.name));
