export * from './auth.js';
export * from './boards.js';
export * from './cities.js';
export * from './notifications.js';
export * from './reports.js';
export * from './report-handling.js';

export const APP_NAME = 'T!indak';

export const ERROR_CODES = Object.freeze({
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  INVALID_JSON: 'INVALID_JSON',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USE_GOOGLE_LOGIN: 'USE_GOOGLE_LOGIN',
  CSRF_REJECTED: 'CSRF_REJECTED',
  BOARD_NOT_FOUND: 'BOARD_NOT_FOUND',
  BOARD_LIMIT_REACHED: 'BOARD_LIMIT_REACHED',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_EXISTS: 'CATEGORY_EXISTS',
  CATEGORY_PROTECTED: 'CATEGORY_PROTECTED',
  CATEGORY_LIMIT_REACHED: 'CATEGORY_LIMIT_REACHED',
  FOLLOW_NOT_FOUND: 'FOLLOW_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  HANDLER_ALREADY_MEMBER: 'HANDLER_ALREADY_MEMBER',
  HANDLER_LIMIT_REACHED: 'HANDLER_LIMIT_REACHED',
  HANDLER_NOT_FOUND: 'HANDLER_NOT_FOUND',
  CANNOT_REMOVE_OWNER: 'CANNOT_REMOVE_OWNER',
  INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',
  INVITATION_NOT_PENDING: 'INVITATION_NOT_PENDING',
  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',
  IMAGE_REJECTED: 'IMAGE_REJECTED',
  CATEGORY_IN_USE: 'CATEGORY_IN_USE',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  INFO_ALREADY_ANSWERED: 'INFO_ALREADY_ANSWERED',
  INVALID_DUPLICATE: 'INVALID_DUPLICATE',
  REOPEN_LIMIT_REACHED: 'REOPEN_LIMIT_REACHED',
});
